### ISSUE TITLE
Doesnt work with Gimp 2.10

### ISSUE THREAD

**Issue by Jeryhn** [gimp-plugins-justice/gimp-deskew-plugin#1]
This plugin is awesome. is there any chance to get it working for Gimp 2.10?
Would be really appreciated.

Thanks again for the awesome work.

**Comment by jdl51** [comment]
I would love deskew to be fixed too. I'm running GIMP 2.10 on linux and facing a massive family photo archiving project. I need the automation of using a "adams divide scanned images" script with the "deskew" plug-in working to straighten everything out.

**Comment by prokoudine** [comment]
@Jeryhn , @jdl51 when built from source code, it works with 2.10 just fine, i've just tried it. Are you referring to the binary file for Windows? Is there an error message?

**Comment by junhochoi-gamedev** [comment]
The Windows binary release tagged v1.1 is failing for me on Gimp 2.10.8
There are three error messages on boot:
![image](https://user-images.githubusercontent.com/24584528/51961898-28dc1000-2413-11e9-9a31-414bed2af448.png)

**Comment by vstepaniuk** [comment]
gimp v2.10.18 :
```
$ ./autogen.sh
...
configure: error: Package requirements (gimp-2.0 >= 2.2.0 gimpui-2.0 >= 2.2.0) were not met:

No package 'gimp-2.0' found
No package 'gimpui-2.0' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables GIMP_CFLAGS
and GIMP_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

Configure failed or did not finish!
```

**Comment by prokoudine** [comment]
Do you have GIMP's dev package installed?

**Comment by vstepaniuk** [comment]
what is its name?

**Comment by vstepaniuk** [comment]
Just installed `libgimp2.0-dev` and it works, Thanks!

**Comment by vstepaniuk** [comment]
Few stupid questions: Where can I find the documentation for the plugin?
Are there any options as to how to determine the rotation angle in order to make plugin run faster? 
How can I process a directory of images on Linux?
How can I choose the newly introduced background color, interpolation type, etc.?
Thanks..

**Comment by prokoudine** [comment]
There are no options whatsoever, it's fully automatic.

You can use https://github.com/alessandrofrancesconi/gimp-plugin-bimp for batch processing :)
