### ISSUE TITLE
Result unchanged from input image.

### ISSUE THREAD

**Issue by pr3sidentspence** [gimp-plugins-justice/gimp-deskew-plugin#2]
Sample image: https://imgur.com/a/PU2K3g8

GIMP 2.8.22 (also an earlier version of 2.8.x, but don't remember which)

EDIT: Windows 10 version 1803 build 17134.345

I copied the 1.1 EXE and two DLLs to the /lib/gimp/2.0/plugin folder and restarted Gimp.

The deskew option is available in the Layer->Transform menu. When selected a progress bar progresses and a Transform Layer operation shows in the Undo History. However, the image is unchanged.

I'm not sure if this is a bug, or I'm doing something wrong, or it can't handle black backgrounds (doesn't seem to work on white, either), etc..

**Comment by prokoudine** [comment]
Well, two things :)

1. Deskew was designed to handle scanned documents, not photos.

2. You will have a lot more luck with GIMP 2.10.6 where you can easily fix rotation with the Measure tool. Just drag a line across the border of your image, then click 'Straighten' button in tool's options dock.

**Comment by pr3sidentspence** [comment]
Ahhh, thanks,

I discovered deskew because it was supported by another Gimp plugin (script, to be precise) [DivideScannedImages](https://github.com/FrancoisMalan/DivideScannedImages). 

Yeah, we've done that in the past, but we're talking tens of thousands of images. I need automation. The good news is I think I've managed to get it working with ImageMagick scripts.

**Comment by jdl51** [comment]
pr3sidentspence,
> Ahhh, thanks,
> 
> I discovered deskew because it was supported by another Gimp plugin (script, to be precise) [DivideScannedImages](https://github.com/FrancoisMalan/DivideScannedImages).
> 
> Yeah, we've done that in the past, but we're talking tens of thousands of images. I need automation. The good news is I think I've managed to get it working with ImageMagick scripts.

How did you manage to get it working using ImageMagick scripts.  I'm facing the same issue with deskew not working on GIMP 2.10 in linux.  I'm trying to archive a bunch of scanned family photos and need to straighten thousands of photos after using "Adams divide scanned images" script.

**Comment by prokoudine** [comment]
Turns out, you can use Deskew for this use case as well, if you crop close enough :)

![2019-01-23 04-31-37](https://user-images.githubusercontent.com/57467/51576564-d1481c80-1ec7-11e9-955e-e880ba4d2648.png)

**Comment by pr3sidentspence** [comment]
PS- It sounds like it's too late for you, but that script will allow one to scan a number of photos at once, and automatically separate, deskew, and crop (leaving some of the background showing) the photos. The only caveat is that there can only be a single column of photos on the scanner. I didn't code a hard limit on the number of photos there could be, but if they get small enough the math will stop working.
