### ISSUE TITLE
Issues with automake-1.16 and gimp-2.10

### ISSUE THREAD

**Issue by wonx** [gimp-plugins-justice/gimp-deskew-plugin#3]
I tried installing it in ubuntu 20.04 according to the instructions. At first, it complained about some dependencies:

    $ ./autogen.sh
    
    I am testing that you have the required versions of autoconf,
    automake, glib-gettextize and intltoolize...
    
    checking for autoconf >= 2.54 ... 
      You must have autoconf installed to compile GIMP Deskew Plug-In.
      Download the appropriate package for your distribution,
      or get the source tarball at ftp://ftp.gnu.org/pub/gnu/
    checking for automake >= 1.6 ... 
      You must have automake 1.6 or newer installed to compile GIMP Deskew Plug-In.
      Download the appropriate package for your distribution,
      or get the source tarball at ftp://ftp.gnu.org/pub/gnu/automake/
    checking for glib-gettextize >= 2.0.0 ... 
      You must have glib-gettextize installed to compile GIMP Deskew Plug-In.
      glib-gettextize is part of glib-2.0, so you should already
      have it. Make sure it is in your PATH.
    checking for intltool >= 0.17 ... 
      You must have intltool installed to compile GIMP Deskew Plug-In.
      Get the latest version from
      ftp://ftp.gnome.org/pub/GNOME/sources/intltool/
    
    Please install/upgrade the missing tools and call me again.

So I installed them by using: 

    $ sudo apt install autoconf automake libglib2.0-dev intltool

I ran the autogen.sh again, but it still complains about automake, despite having version *1:1.16.1-4ubuntu6* installed.

     $ ./autogen.sh
    
    I am testing that you have the required versions of autoconf,
    automake, glib-gettextize and intltoolize...
    
    checking for autoconf >= 2.54 ... 1
    yes (version 2.69)
    checking for automake >= 1.6 ... 
      You must have automake 1.6 or newer installed to compile GIMP Deskew Plug-In.
      Download the appropriate package for your distribution,
      or get the source tarball at ftp://ftp.gnu.org/pub/gnu/automake/
    checking for glib-gettextize >= 2.0.0 ... 1
    yes (version 2.64.3)
    checking for intltool >= 0.17 ... 1
    yes (version 0.51.0)
    
    Please install/upgrade the missing tools and call me again.

    
So I assumed the script is not prepared to detect automake 1.16. I edited it to add the option for that version

    elif (automake-1.16 --version) < /dev/null > /dev/null 2>&1; then
       AUTOMAKE=automake-1.16
       ACLOCAL=aclocal-1.16

But now it ends with this error:

    (...)
    checking for GIMP... no
    configure: error: Package requirements (gimp-2.0 >= 2.2.0 gimpui-2.0 >= 2.2.0) were not met:
    
    No package 'gimp-2.0' found
    No package 'gimpui-2.0' found
    
    Consider adjusting the PKG_CONFIG_PATH environment variable if you
    installed software in a non-standard prefix.
    
    Alternatively, you may set the environment variables GIMP_CFLAGS
    and GIMP_LIBS to avoid the need to call pkg-config.
    See the pkg-config man page for more details.
    
    Configure failed or did not finish!

I guess it expects gimp-2.0, but gimp-2.1 is installed in my system.

Any idea?

**Comment by prokoudine** [comment]
$ sudo apt-get install libgimp2.0-dev

**Comment by wonx** [comment]
Thank you, works perfectly.

So for future reference, all I had to do in Ubuntu 20.04 was:

```
sudo apt install autoconf automake libglib2.0-dev intltool libgimp2.0-dev checkinstall
./autogen.sh
make
sudo checkinstall -D make install
```

Maybe these dependencies could be listed in the install section?
